# TagSpaces

## File Management
### Browse Files
### Search Files
### File Preview

## Tagging System
### Color Tags
### Smart Tags
### Tag Groups
### Geo Tags

## Extensions
### Viewers
#### Image Viewer
#### PDF Viewer
#### HTML Viewer
#### Media Player
### Editors
#### Markdown Editor
#### Text Editor
#### HTML Editor
#### JSON Editor

## Platforms
### Desktop
#### Windows
#### macOS
#### Linux
### Mobile
#### Android
### Web
#### Browser App
